<?php

    $num = shell_exec("ls picture/suits | wc -l");
//    for( $temp_i = 1 ; $temp_i <= 30 ; $temp_i++ )
//    {
	
        $img = 9;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
	    $img = 197;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 198;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 247;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 271;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 284;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 291;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 303;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 307;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 504;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 519;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 612;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 613;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 684;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 685;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 1095;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 1157;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 1158;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 164;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 144;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 130;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 10;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 12;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 16;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 19;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 20;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 21;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 25;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 59;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 70;
        echo $img;
        echo "<img src=\"picture/tops/$img.jpg\" width=\"450\" >";
        $img = 27;
        echo $img;
        echo "<img src=\"picture/bottoms/$img.jpg\" width=\"450\" >";
        $img = 27;
        echo $img;
        echo "<img src=\"picture/bottoms/$img.jpg\" width=\"450\" >";
        $img = 6;
        echo $img;
        echo "<img src=\"picture/bottoms/$img.jpg\" width=\"450\" >";
        $img = 8;
        echo $img;
        echo "<img src=\"picture/bottoms/$img.jpg\" width=\"450\" >";
        $img = 118;
        echo $img;
        echo "<img src=\"picture/bottoms/$img.jpg\" width=\"450\" >";
        $img = 117;
        echo $img;
        echo "<img src=\"picture/bottoms/$img.jpg\" width=\"450\" >";
        $img = 109;
        echo $img;
        echo "<img src=\"picture/bottoms/$img.jpg\" width=\"450\" >";
        $img = 17;
        echo $img;
        echo "<img src=\"picture/bottoms/$img.jpg\" width=\"450\" >";
        $img = 63;
        echo $img;
        echo "<img src=\"picture/bottoms/$img.jpg\" width=\"450\" >";
        $img = 3;
        echo $img;
        echo "<img src=\"picture/bottoms/$img.jpg\" width=\"450\" >";

//    }
	
?>
