#!/bin/sh
PATH='/var/www/html/project'

#start permutation'
$PATH/recommand/permutation $PATH/users/$1/mytops $PATH/users/$1/mybottoms $PATH/users/$1/pResult
#$PATH/recommand/permutation $PATH/mytops $PATH/users/mybottoms $PATH/users/pResult
/bin/rm -f /var/lib/mysql/dressing/result

#fetch data from database
/usr/bin/mysql -uroot -p12345 < $PATH/recommand/mysqlscript

#fix the data 
/bin/mv /var/lib/mysql/dressing/result $PATH/users/$1/temp
/bin/cat $PATH/users/$1/temp | /bin/sed 's/\\$//' > $PATH/users/$1/mysuits_data
/bin/rm $PATH/users/$1/temp

#calculate score
/usr/bin/octave $PATH/recommand/recommand.m $1 
$PATH/recommand/showResult $1
