#!/bin/bash
PATH="/var/www/html/project/users"
recommandList=`/bin/cat $PATH/$1/myscore | /bin/grep '^ 0' | /bin/cat -n | /usr/bin/sort -k2 -r | /usr/bin/cut -f1`
/bin/rm -f temp_file
for temp in $recommandList
    do
        echo `/usr/bin/head -$temp $PATH/$1/pResult | /usr/bin/tail -1`
    done
